[1-1]
tilemap = """
->v-------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=----------------------------------000-------------------------------------------
-=---------------------------------0----------------------------------------------
-=--------------------------------0--======----@--G---x---------------------------
-=-----------------------------------======----=====------------------------------
-=-------------------------x?x------x====-----------------------------------------
-=-------------------------------========---------------------------------x---x---
-=-------------------------------========--------------------------------xx---xx--
-=------------------------------x========-G---=-------------------------xxx---xxx-
===========================================================================---====
===========================================================================###====
"""
