[F-1]
tilemap = """
>----------------------------------------------------------------------------------v
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=-----------------------------------000--------------------------------------------=
=----------------------------------0-----------------------------------------------=
=---------------------------------0--======----------------------------------------=
=------------------------------------======----------------------------------------=
=--------------------------x?x------x====------------------------------------------=
=--------------------------------========---------------------------------xx--======
=--------------------------------========-G------------------------------xxx--======
=----------------------@--------x======================-----------------xxxx--======
============================================================================--======
============================================================================--=====<
============================================================================##=====^
"""
