[1-1]
tilemap = """
->------------------------------------------------------------------------------
->------------------------------------------------------------------------------
->------------------------------------------------------------------------------
->------------------------------------------------------------------------------
->------------------------------------------------------------------------------
->------------------------------------------------------------------------------
->------------------------------------------------------------------------------
->------------------------------------------------------------------------------
->------------------------------------------------------------------------------
->------------===-===-----------------------------------------------------------
->------------===---------------------------------------------------------------
->------------===--=------------------------------------------------------------
->------------------------------------------------------------------------------
->---------------------------------------------x--------------------------------
->-------------------------x?x----------------xxx-------------------------------
->------------000----------------------------xxxxx------------------------------
->--@---------------------------------------xxxxxxx-----------------------------
================================================================================
=^==============================================================================
"""
