[1-1]
tilemap = """
->v-------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=--------------------------------------------------------------------------------
-=----------------------------------000-------------------------------------------
-=---------------------------------0-----@----------------------------------------
-=--------------------------------0--======---------------------------------------
-=-----------------------------------======---------------------------------------
-=-------------------------x?x------x====-----------------------------------------
-=-------------------------------========---------------------------------x---x---
-=-------------------------------========--------------------------------xx---xx--
-=------------------------------x========-G---=-------------------------xxx---xxx-
===========================================================================---====
===========================================================================###====
"""
