[F-1]
music="athletic"
special=[]
background="hills"
tilemap = """
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=------------------------------------------------------------------------==--------=
=------------------------------------------------------------------------==~~~======
=-----------------------------------------------------------------------------======
=--------------------------------------------------------------------------------===
=------------------------------------------------------------=========-------------=
=-----------------------------------------------------------===========------------=
=-----------------------------------------------------------===========---CC-------=
=------------------------------------------------------------===========-----------=
=-----------------------------------000-------------------------========-----------=
=----------------------------------0------------------------------======-----CCC---=
=----------000--------------------0--=========~~~~====xxx====-=-=-=====------------=
=------------------------------------======--------=========-----------------------=
=----------x??x----------------------====-----------=======---------------------PP-=
=----------------------------0---========------------======--00000000-----PP----PP-=
=-------------------------000---=========-G---------=======--00000000--PP-PP----PP-=
=---@->------------------------============================------------PP-PP-------=
=============================================================================------=
=============================================================================------=
=============================================================================######=
"""
