[F-1]
music="athletic"
special=[]
background="clouds"
tilemap = """
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=------------------------------------------------------------=========-------------=
=-----------------------------------------------------------============-----------=
=-----------------------------------------------------------============-----------=
=------------------------------------------------------------===========-----------=
=-----------------------------------000-------------------------========-----------=
=----------------------------------0-----------------@------------=====------------=
=----------000--------------------0--=========~~~~===========-=-=-=====------------=
=------------------------------------======--------=========-----------------------=
=----------x?x-----------------------====-----------=======------------------------=
=----------------------------0---========------------======--00000000-----xx--======
=-------------------------000---=========-G---------=======--00000000----xxx--======
=----->------------------------============================-------------xxxx--======
============================================================================--======
============================================================================--======
============================================================================##======
"""
