[F-1]
music="kapper-valley"
special=[]
background="valley"
tilemap = """
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=------------------------------------------------------------------------==--------=
=------------------------------------------------------------------------==~~~======
=-----------------------------------------------------------------------------======
=--------------------------------------------------------------------------------===
=------------------------------------------------------------=========-----CCC-----=
=-----------------------------------------------------------===========------------=
=-----------------------------------------------------------===========------------=
=------------------------------------------------------------===========-----------=
=-----------------------------------000-------------------------========-----------=
=----------------------------------0------@----------@------------======-----------=
=----------000--------------------0--=========~~~~====xxx====-=-=-=====------------=
=------------------------------------======--------=========-----------------------=
=----------x?x-----------------------====-----------=======------------------------=
=----------------------------0---========------------======--00000000-----xx--======
=-------------------------000---=========-G---------=======--00000000----xxx--======
=----->------------------------============================-------------xxxx--======
============================================================================--======
============================================================================--======
============================================================================##======
"""
