[F-1]
music="athletic"
background="grassland"
tilemap = """
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=----------------------------------------------------------------------------------=
=-----------------------------------000--------------------------------------------=
=----------------------------------0-----------------------------------------------=
=----------000--------------------0--======----@--G---x----------------------------=
=------------------------------------======----=====-------------------------------=
=---------xx?xx----------------------====------------------------------------------=
=---------------------------0----========---------------------------------xx--======
=------------------000000000----=========-G------------------------------xxx--======
=--@-->------------------------========================-----------------xxxx--======
============================================================================--======
============================================================================--======
============================================================================##======
"""
